const express = require("express");

const app = express();
const port = process.env.PORT || 3000;

app.disable("x-powered-by");

const fs = require("fs");
const page = fs.readFileSync("public/homepage-cathedral.html", "utf8");

app.use(express.json({ limit: "2mb" }));
app.use(express.static("public", { extensions: ["svg"] }));


const deepPage = (title, kicker, body) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#070707"><title>${title} · Identity Field Dynamics</title><style>body{margin:0;background:#050505;color:#eeeae1;font-family:Inter,system-ui,sans-serif}main{width:min(900px,calc(100% - 40px));margin:auto;padding:100px 0}a{color:#f3da8c;text-decoration:none}.k{color:#d6b15a;font-size:11px;letter-spacing:.25em;text-transform:uppercase}h1{font-size:clamp(44px,8vw,82px);line-height:.95;letter-spacing:-.05em;margin:20px 0 30px}p{color:#aaa9a4;font-size:18px;line-height:1.8}.panel{border-top:1px solid #292929;margin-top:55px;padding-top:35px}.back{font-size:11px;letter-spacing:.16em;text-transform:uppercase}</style></head><body><main><a class="back" href="/">← Identity Field Dynamics</a><div class="panel"><div class="k">${kicker}</div><h1>${title}</h1>${body}</div></main></body></html>`;
app.get("/research/memoranda", (_req,res)=>res.type("html").send(deepPage("Research Record","03A / Foundational Memoranda",`
<p>The Research Record preserves foundational memoranda as an intact chronological archive. A memorandum records what the investigation considered necessary to question at a particular point in time. Later developments may supersede its assumptions, but they do not silently rewrite the record.</p>
<div class="panel"><div class="k">IFD-MEM-001 · September 26, 2026</div><h2 style="font-size:38px">Foundational Status of W</h2><p><strong>W?</strong></p><p><strong>What observation would distinguish W as an element of Identity from W as a pre-identity platform?</strong></p><p><strong>We do not yet know.</strong><br>The question arose from theoretical analysis and phenomenological experience. It remains an empirical question.</p><p>Our investigation has reached a point at which a foundational assumption must be reconsidered.</p><p>We have been treating <strong>W (Witness)</strong> as a possible component or stage in the development of Identity. We now recognize that this may be the wrong starting assumption.</p><p>Accordingly, we will not build further instrumentation on the assumption that W is already established as an identity construct.</p><p>We will instead build the <strong>right machine</strong>: an experimental system capable of distinguishing among competing possibilities without presupposing the answer.</p><p>The theoretical architecture remains available as a hypothesis. The empirical question remains open.</p><p><strong>The machine comes before the conclusion.</strong></p><div class="panel"><div class="k">Scientific posture</div><p>We are not building a machine to confirm W. We are building a machine capable of discovering whether W needs to exist as a construct at all.</p></div><div class="panel"><div class="k">Current status</div><p><strong>W</strong> · ?<br><strong>Identity</strong> · ?<br><strong>Machine</strong> · UNDER CONSTRUCTION<br><strong>Question</strong> · OPEN</p></div></div>`)));
app.get("/research/memoranda/w-001", (_req,res)=>res.type("html").send(deepPage("Foundational Status of W","IFD-MEM-001 · September 26, 2026",`
<p><strong>W?</strong></p>
<p><strong>What observation would distinguish W as an element of Identity from W as a pre-identity platform?</strong></p>
<p><strong>We do not yet know.</strong><br>The question arose from theoretical analysis and phenomenological experience. It remains an empirical question.</p>
<p>Our investigation has reached a point at which a foundational assumption must be reconsidered.</p>
<p>We have been treating <strong>W (Witness)</strong> as a possible component or stage in the development of Identity. We now recognize that this may be the wrong starting assumption.</p>
<p>Accordingly, we will not build further instrumentation on the assumption that W is already established as an identity construct.</p>
<p>We will instead build the <strong>right machine</strong>: an experimental system capable of distinguishing among competing possibilities without presupposing the answer.</p>
<p>The theoretical architecture remains available as a hypothesis. The empirical question remains open.</p>
<p><strong>The machine comes before the conclusion.</strong></p>
<div class="panel"><div class="k">Scientific posture</div><p>We are not building a machine to confirm W. We are building a machine capable of discovering whether W needs to exist as a construct at all.</p></div>
<div class="panel"><div class="k">Current status</div><p><strong>W</strong> · ?<br><strong>Identity</strong> · ?<br><strong>Machine</strong> · UNDER CONSTRUCTION<br><strong>Question</strong> · OPEN</p></div>
`)));
app.get("/discipline", (_req,res)=>res.type("html").send(deepPage("The Discipline","01 / Discipline",`<p><strong>Identity Field Dynamics (IFD)</strong> is the developing discipline that emerged from work first developed under the working name <em>Identity Physics</em>.</p><p>The distinction is substantive: Identity Physics names the discovery and its early working architecture; Identity Field Dynamics names the broader discipline built around identity as a dynamic, structured field system.</p><div class="panel"><div class="k">The central question</div><p>What happens when identity is treated not as a fixed label or isolated trait, but as a system whose components can interact, persist, respond to perturbation, and change state?</p></div><div class="panel"><div class="k">The field</div><p>In IFD, “field” is a working model for describing distributed structure and interaction. It is not presented as a claim that identity is a physical force. The model earns its standing through operational definitions, observable consequences, competing explanations, and empirical tests.</p></div><div class="panel"><div class="k">The discipline</div><p>IFD connects candidate constructs to measurement, coupling hypotheses, dynamic models, phase and transition analysis, and systematic revision. Its canonical architecture is intentionally separated from the evidence used to evaluate it.</p></div><div class="panel"><div class="k">Historical transition</div><p><strong>IDENTITY PHYSICS was the name of the discovery.</strong><br>IDENTITY FIELD DYNAMICS is the name of the discipline that emerged from it.</p></div>`)));
app.get("/framework", (_req,res)=>res.type("html").send(deepPage("The Framework","02 / Framework",`<p>W, V, B, A, N, and D are <strong>candidate axes</strong> of a coupled identity field. They are not presented as six independently validated dimensions.</p><div class="panel"><div class="k">W / Witness</div><p>Detection, noticing, monitoring, and orientation.</p></div><div class="panel"><div class="k">V / Vector</div><p>Directionality and the reconstruction of directional choice.</p></div><div class="panel"><div class="k">B / Being / Boundary</div><p>Persistence, stability, and boundary conditions.</p></div><div class="panel"><div class="k">A / Archetype / Abstraction</div><p>Pattern abstraction and higher-order representation.</p></div><div class="panel"><div class="k">N / Narrative</div><p>The organization of identity through narrative structure.</p></div><div class="panel"><div class="k">D / Distortion</div><p>Deviation, transformation, and identity-system perturbation.</p></div><div class="panel"><div class="k">From axes to dynamics</div><p>The research question is not merely whether these constructs can be separated. It is whether they interact in structured ways: coupling, reinforcement, constraint, perturbation response, persistence, and transition. Those relationships remain hypotheses to be tested.</p></div>`)));
app.get("/research", (_req,res)=>res.type("html").send(deepPage("The Research Program","03 / Research",`<p>IFD moves from proposition to test through a deliberate chain: <strong>Operationalize → Observe → Perturb → Compare → Falsify → Revise.</strong></p><p>The deeper research layer will house H1–H8, preregistration, protocols, model comparisons, results, failures, revisions, and the evidentiary status of individual claims.</p><p>Research artifacts will remain linked to their provenance so that the history of a claim is visible rather than rewritten after the fact.</p>`)));
app.get("/lab", (_req,res)=>res.type("html").send(deepPage("The LAB","03A / Active Experimental Chamber",`
<p><strong>Do something before you read what it means.</strong> The first LAB prototype is deliberately small: a sequence appears, you choose what comes next, and the system records the choice. There is no canonical score and no correct answer being assigned to you.</p>
<div class="panel">
<div class="k">LAB 001 · Pattern &amp; Prediction</div>
<h2>What do you expect next?</h2>
<p>Observe the sequence. Choose the symbol that you think follows the rule you noticed.</p>
<div id="lab-seq" style="font-size:clamp(34px,7vw,64px);letter-spacing:.22em;margin:28px 0;color:#f3da8c;font-family:ui-monospace,SFMono-Regular,Menlo,monospace">B B A A</div>
<div style="display:flex;gap:14px;flex-wrap:wrap">
<button class="button" onclick="choose('A')">A</button>
<button class="button" onclick="choose('B')">B</button>
</div>
<p id="lab-msg" style="min-height:32px;margin-top:24px"></p>
</div>
<div class="panel">
<div class="k">What was just observed?</div>
<p>You made an action under a simple, ambiguous pattern-recognition task. The prototype records the sequence shown, your response, and the time of the response. It does <em>not</em> turn that action into a validated W/V/B/A/N/D score.</p>
</div>
<div class="panel">
<div class="k">Why begin here?</div>
<p>The IFD research program is interested in what can be learned from behavior rather than merely what a person says about themselves. A tiny experiment lets us start with an observable action, then ask what information that action can legitimately support.</p>
</div>
<div class="panel">
<div class="k">Research status</div>
<p>This is a public research prototype, not a validated psychological instrument. Its purpose is to develop the measurement architecture and expose the logic of the investigation.</p>
</div>
<script>
const started=performance.now();
function choose(choice){
  const elapsed=Math.round(performance.now()-started);
  document.getElementById('lab-msg').textContent='Recorded: '+choice+' · response time '+elapsed+' ms';
  document.querySelectorAll('.button').forEach(b=>b.disabled=true);
}
</script>`)));;
app.get("/observor", (_req,res)=>res.type("html").send(deepPage("OBSERVOR","Measurement Infrastructure",`<p>OBSERVOR is the developing measurement and discovery engine supporting the IFD empirical program. It is designed around durable session integrity and research-data lineage.</p><p>The deeper OBSERVOR layer will document instruments, missions, event schemas, integrity controls, and the path from participant action to research observation.</p>`)));
app.get("/codex", (_req,res)=>res.type("html").send(deepPage("The Codex","04 / Canonical Knowledge Architecture",`<p>The Codex is the canonical knowledge architecture of IFD: definitions, notation, claims, constructs, variables, equations, experiments, evidence status, and historical provenance.</p><p>It is intended to make the evolving discipline inspectable without pretending that unfinished material is already canonical.</p>`)));
app.get("/confessional", (_req,res)=>res.type("html").send(deepPage("The Confessional","05 / A living human archive",`<p>Humans do not enter the cathedral merely to receive a finished doctrine. They enter to <strong>observe, question, disagree, connect, and speak.</strong></p><div class="panel"><div class="k">The founding principle</div><p><strong>No experience is automatically evidence.</strong><br>No experience is automatically dismissed.<br><br>Bring it. Examine it. Test it.</p></div><div class="panel"><div class="k">The living archive</div><p><strong>Observation → discussion → question → research → evidence → Codex revision.</strong></p><p>The Confessional does not decide what becomes scientific knowledge. Evidence does. A community contribution may become a research question; a tested result may later change the Codex. The original conversation remains part of the record.</p></div><div class="panel"><div class="k">Founding entries</div><p><strong>001 · Who better than humans to speak to identity?</strong><br>A place for lived observation, experience, and questions about identity.</p><p><strong>002 · Tell us when you think we're wrong.</strong><br>Serious disagreement, alternative explanations, and uncomfortable questions remain visible rather than being edited out.</p></div><div class="panel"><div class="k">Community layer</div><p>Threaded discussion and public posting will be added as the next infrastructure layer. Before permanent submissions enter the archive, the system will establish durable provenance, moderation, anti-spam, and abuse protections.</p></div><div class="panel"><div class="k">The standard</div><p><strong>Bring your certainty. Bring your doubt. Bring your disagreement. Just bring your reasons.</strong></p></div>`)));
app.get("/about", (_req,res)=>res.type("html").send(deepPage("About Us","ABOUT US / The research behind the discipline",`
<p><strong>Identity Field Dynamics is the discipline. Identity Research is the work.</strong></p>
<div class="panel"><div class="k">The Identity Researcher</div><h2 style="font-size:38px">What is an Identity Researcher?</h2><p>An Identity Researcher investigates identity as a phenomenon.</p><p>Rather than beginning with an assumption about what identity must be, an Identity Researcher asks what identity is, how it forms, how it persists, how it changes, and what can actually be observed about its dynamics.</p><p><strong>The mission of the researcher is to investigate the nature, structure, dynamics, and observability of identity—and to discover what is actually true about it.</strong></p><div class="cta"><a class="button primary" href="/about/identity-researcher">Read The Identity Researcher</a></div></div>
<div class="panel"><div class="k">The IFD Mission</div><h2 style="font-size:38px">What does Identity Field Dynamics exist to do?</h2><p>Identity Field Dynamics exists to investigate the nature, structure, dynamics, and observability of identity—and to develop the theoretical and empirical means necessary to determine what is actually true about it.</p><p><strong>IFD must be capable of being wrong.</strong></p><p>The work moves forward either way.</p><div class="cta"><a class="button primary" href="/about/mission">Read The IFD Mission</a></div></div>
<div class="panel"><div class="k">Orientation</div><p>The researcher serves the research. The research serves the discovery of what is true.</p></div>`)));
app.get("/about/identity-researcher", (_req,res)=>res.type("html").send(deepPage("The Identity Researcher","ABOUT US / Personal vocational mission",`
<p>An Identity Researcher investigates identity as a phenomenon.</p>
<p>Rather than beginning with an assumption about what identity must be, an Identity Researcher asks what identity is, how it forms, how it persists, how it changes, and what can actually be observed about its dynamics.</p>
<p>The work may draw upon philosophy, science, psychology, systems theory, behavioral observation, mathematics, and other fields of inquiry—but it is not confined to any one of them.</p>
<div class="panel"><div class="k">What does an Identity Researcher do?</div><p>An Identity Researcher develops questions into testable propositions: identifying constructs, defining relationships, developing methods of observation and measurement, examining evidence, and revising or rejecting propositions when the evidence requires it.</p><p><strong>The objective is not to prove a preferred theory. The objective is to discover whether the theory survives investigation.</strong></p></div>
<div class="panel"><div class="k">The Researcher's Mission</div><p><strong>To investigate the nature, structure, dynamics, and observability of identity—and to discover what is actually true about it.</strong></p></div>
<div class="panel"><div class="k">Relationship to IFD</div><p>Identity Field Dynamics is the discipline that emerged from pursuing this inquiry.</p></div>`)));
app.get("/about/mission", (_req,res)=>res.type("html").send(deepPage("The IFD Mission","ABOUT US / Mission of Identity Field Dynamics",`
<p><strong>Identity Field Dynamics exists to investigate the nature, structure, dynamics, and observability of identity—and to develop the theoretical and empirical means necessary to determine what is actually true about it.</strong></p>
<div class="panel"><div class="k">The mission</div><p>Not to defend a predetermined theory. Not to establish a doctrine. Not to prove that Identity Field Dynamics is correct.</p><p><strong>To find out what is true about identity.</strong></p></div>
<div class="panel"><div class="k">Four commitments</div><p><strong>Understand.</strong> Investigate what identity is, what constitutes it, and what distinguishes identity from related phenomena.</p><p><strong>Model.</strong> Develop formal representations of identity and its dynamics.</p><p><strong>Observe.</strong> Develop methods for investigating identity through observable phenomena.</p><p><strong>Test.</strong> Subject IFD's own propositions to investigation and permit evidence to modify, refine, or reject them.</p></div>
<div class="panel"><div class="k">The essential condition</div><p><strong>IFD must be capable of being wrong.</strong></p><p>A framework that cannot be contradicted cannot function as an empirical research program. Constructs may be revised. Models may be replaced. Hypotheses may fail. Methods may prove inadequate. Conclusions may change.</p><p><strong>That is not a failure of the mission. That is the mission working.</strong></p></div>
<div class="panel"><div class="k">From discovery to discipline</div><p><strong>IDENTITY PHYSICS was the name of the discovery.</strong><br>IDENTITY FIELD DYNAMICS is the name of the discipline that emerged from it.</p></div>
<div class="panel"><div class="k">The objective</div><p>The ultimate objective of IFD is not the preservation of IFD itself. It is the advancement of knowledge about identity.</p><p><strong>The work moves forward either way.</strong></p></div>
<div class="panel"><div class="k">The mission in one sentence</div><p style="font-size:24px;color:#f3da8c"><strong>Identity Field Dynamics exists to discover what is actually true about identity.</strong></p></div>`)));

app.get("/", (_req, res) => res.type("html").send(page));
app.listen(port, () => console.log(`Identity Field Dynamics listening on port ${port}`));
